spring:
  application:
    name=store-api
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root@2017
  jpa:
    show-sql: true
server:
  port:8085